# Generated by Django 3.0.7 on 2020-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
